apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log_output
  template:
    metadata:
      labels:
        app: log_output
    spec:
      containers:
        - name: log-output-container
          image: jouchef/log_output:1.1