apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: ping-claim
      containers:
        - name: log-creator-container
          image: jouchef/log-creator:1.11.1
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
        - name: log-reader-container
          image: jouchef/log-reader:2.1.3
          env:
            - name: PORT
              value: "3004"
            - name: SVC-PORT
              value: "2345"
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
