apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: server-claim
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-claim
      containers:
        - name: server-container
          image: jouchef/server:2.2.7
          env:
            - name: FRONT-PORT
              value: "3006"
          volumeMounts:
            - name: server-volume
              mountPath: /app/static
        - name: backend-container
          image: jouchef/backend:2.2.4
          env:
            - name: BACKEND-PORT
              value: "3007"
          volumeMounts: 
            - name: db-volume
              mountPath: /app/db