apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: server-claim
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-claim
      containers:
        - name: server-container
          image: jouchef/server:1.13.5
          env:
            - name: PORT
              value: "3006"
          volumeMounts:
            - name: server-volume
              mountPath: /app/static
            - name: db-volume
              mountPath: /app/data/db