apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server-container
          image: jouchef/server:1.5
          #imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: PORT
