apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: server-claim
      containers:
        - name: server-container
          image: jouchef/server:2.6.1
          env:
            - name: FRONT-PORT
              value: "3006"
            - name: BACKENDSVCURL
              value: "backend-svc"
            - name: SVCPORT
              value: "2345"
            - name: IMGCACHETIME
              value: "600"  #seconds
            - name: IMAGEPATH
              value: "images/kuva.jpg"   # This directory will be inside of /static
            - name: PICURL
              value: "https://picsum.photos/300/200.jpg"
          volumeMounts:
            - name: server-volume
              mountPath: /app/static
        - name: backend-container
          image: jouchef/backend:2.8.2
          env:
            - name: BACKEND-PORT
              value: "3007"
            - name: DB_HOST
              value: "todo-postgres-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "tododb"
            - name: DB_USER
              value: "todo"
            - name: DB_PASSWORD
              value: "secretpassword"