apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: server-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: db-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi