apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim # name of the volume claim, this will be used in the deployment
  namespace: exercises
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
